# Generated by Django 4.2.11 on 2024-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('date_vu', models.DateField(blank=True)),
                ('localisation', models.CharField(max_length=30)),
            ],
        ),
    ]
